// SPDX-FileCopyrightText: 2019 M. Shulhan <ms@kilabit.info>
// SPDX-License-Identifier: GPL-3.0-or-later
= Changelog for awwan

== awwan v0.5.0 (2022-03-14)

This release re-lincesing the awwan software under GPL 3.0 or later.

See https://kilabit.info/journal/2022/gpl for more information.


==  awwan 0.4.0 (2022.02.05)

This release bring new command "serve" to awwan.
The serve command run HTTP server that provide web-user interface to create,
edit, save, and execute script.

===  New features

*  all: implement HTTP API and function to Save file on web-user interface
+
The web-user interface now have button "Save" that save the edited
content of file to storage.

*  all: implement serve command
+
--
The serve command will run a HTTP server that provide web-user interface
to edit and execute script.

Currently, the web-user interface provide the following features,

* Browsing the workspace
* Running the script on local or remote
--

=== Enhancements

*  all: make the local statement executed with "/bin/sh -c ..."
+
By using "sh -c", the statement can contains environment variable,
piping, and other shell commands that cannot be supported if executed
directly using native os.Exec.

*  all: expand the environment on statement when executing local script
+
This changes replace the string ${x} or $x in the statements with the
current environment variables values.
+
For example, statement "mkdir ${HOME}/tmp" will expand the ${HOME} to
the current user home directory.

*  all: use native SFTP to put and get file when possible
+
Previously, the command to put and get file from remote server depends
on installed scp program on the host computer.
+
In this changes we add the SFTP client and use it as primary function
to put and get file to/from remote when possible and use the scp as
fallback.


==  awwan 0.3.0 (2021.06.09)

* go.mod: set the minimum Go to 1.16 and update to share module v0.25.1

=== Enhancements

* cmd/awwan: print the awwan version on command usage output

* all: check and return an error if start index is out of range

* all: log error when executing script (local or play)

* all: do not load SSH config if command mode is "local"
+
If the mode is local there is no need to parse and load the SSH config,
since the command to be executed will run on local machine anyway.

* all: set base dir based on the first .ssh directory that we found
+
Previously, the base directory is set on current working directory.
This limit the way to execute awwan only from the directory
that contains the .ssh directory.
+
This changes set the environment BaseDir based on the first .ssh
directory that we found from script path up to the "/".  So, user can
execute awwan script from any sub-directories.


==  awwan 0.2.1 (2021.01.18)

Update the share modules which bring fixes to "#put" commands.


==  awwan 0.2.0 (2020.07.05)

===  New features

*  environment: export the SSH key, user, host, and port
+
--
By knowing this values, user can use it to invoke other SSH related
command, for example to copy file using `scp`

  scp -i {{.SSHKey}} src {{.SSHUser}}@{{.SSHHost}}:{{.SSHPort}}/dst
--

*  all: add magic command "#require:"
+
--
Magic word `#require:` will ensure that the next statement will always
executed when its skipped with start number.
For example, given following script with line number

----
1: #require:
2: echo a
3: echo b
4: #require:
5: echo c
----

executing `awwan local script.aww 3`, will always execute line
number 2 `echo a`, but not line number 5 (because its before line start 3).
--

===  Bug fixes

*  command: change the owner of file when doing #get!
+
In case the owner of file is not active user and it does not have
read permission, the "#get!" command will fail when copying command
from remote to local.

*  command: fix magic copy and get command on templates

===  Enhancements

*  command: merge sequences of spaces on command into single space

*  command: check for single, double, or back quote on command
+
--
Previously, if command contains quote like,

	echo "a b"

the script will run it as ["echo", `"a`, `b"`] which is not what we
will expected and may cause some command failed to run.

This changes fix the parsing of command string by detecting possible
quote.
--

==  awwan 0.1.0 (2020.05.30)

Its better late than never.

The first release works for everyday use.
The `local`, `play` command works as it is, and its has been used for
deploying and managing postfix, dovecot, haproxy, and my personal server and
services at kilabit.info.
Also it has been used to deploy Go microservices using Kubernetes using
combination of `gcloud` and `kubectl`.
