= Changelog for awwan

==  awwan 0.2.0 (2020.06.xx)

===  New features

*  all: add magic command "#require:"

Magic word `#require:` will ensure that the next statement will always
executed when its skipped with start number.
For example, given following script with line number

  1: #require:
  2: echo a
  3: echo b
  4: #require:
  5: echo c
```

executing `awwan local script.aww 3`, will always execute line
number 2 `echo a`, but not line number 5 (because its before line start 3).


===  Enhancements

*  command: merge sequences of spaces on command into single space

*  command: check for single, double, or back quote on command

Previously, if command contains quote like,

	echo "a b"

the script will run it as ["echo", `"a`, `b"`] which is not what we
will expected and may cause some command failed to run.

This changes fix the parsing of command string by detecting possible
quote.


==  awwan 0.1.0 (2020.05.30)

Its better late than never.

The first release works for everyday use.
The `local`, `play` command works as it is, and its has been used for
deploying and managing postfix, dovecot, haproxy, and my personal server and
services at kilabit.info.
Also it has been used to deploy Go microservices using Kubernetes using
combination of `gcloud` and `kubectl`.
