= awwan

awwan is configuration management software, infrastructure as file and
directory layout.

In other words, `awwan` is a command-line interface (CLI) to shell script,
that can execute multiple lines of commands in local or remote server using
shell or SSH.

Do you have a collection of shell scripts to manage one more similar server?
Do you ever want to execute only part of your script?
Are you get tired with learning others syntax and tools for provisioning
your own server, while you need is a handful knowledge of shell script?

If yes, awwan is the right tools for you.

Features,

- Encryption. Awwan can read and copy encrypted files.
- Encrypted variables. Awwan can read and executed script that contains
  encrypted variables.
- Dynamic script with variables. An awwan script is like shell script but
  can be executed in different remote servers with different values.
- Dynamic script execution. Unlike shell script, awwan can select which
  lines to be executed, either by number or by range.
- Provisioning in local environment using basic shell.
- Provisioning in remote server using SSH and SFTP.

From the CLI perspective, awwan is feature complete.

Most enhancements and bug fixes probably in the web user interface with
clear use cases and issues.

Feel free to open new feature or report a bug in our
https://todo.sr.ht/~shulhan/awwan[issue tracker].


==  Documentation

link:CHANGELOG.html[CHANGELOG] --
History of each awwan release.

link:install.html[Installation] --
Link to download and/or install awwan manually from source code.

link:awwan.html[Manual page] --
The manual page describe how to setup and use awwan.


==  Development

https://git.sr.ht/~shulhan/awwan[Repository] --
The repository of this software project.

https://lists.sr.ht/~shulhan/awwan[Mailing list] --
Place for discussion and sending patches.

https://todo.sr.ht/~shulhan/awwan[Issues] --
Place to open new issue or request for new feature.
