// SPDX-FileCopyrightText: 2019 M. Shulhan <ms@kilabit.info>
// SPDX-License-Identifier: GPL-3.0-or-later
= Changelog for awwan
:toc:
:sectanchors:
:sectlinks:


[#v0_6_2]
==  awwan v0.6.2 (2023-03-03)

This release set minimum Go to 1.18 and update all dependencies.

[#v0_6_2__chores]
===  Chores

all: fix the git clone URL in README::
+
The clone URL should be in https scheme to make works for non-authenticated
user.


all: restructure the documents::
+
--
Changes,

* Store all documents into directory _doc. This changes make the
  directory doc inside _www become symlinks.
* Move CHANGELOG.adoc to _doc
* Rename README.adoc to README so it can be rendered on git.sr.ht, and
  make it symlink so it can still rendered as AsciiDoc on GitHub.
* Add To-do to _doc/index.adoc that was previously uncommitted as NOTEs
--


[#v0_6_1]
==  awwan v0.6.1 (2022-08-06)

This release fix the build process due to unused dependencies, private
submodules URL, and missing directory; which is not caught when running on
local.

[#v0_6_1_chores]
===  Chores

all: remove calling tsc when building main.js::
+
--
The main.js already build with esbuild.
--

all: add empty .ssh directory to allow running build command::

all: changes the submodule wui to use https schema::
+
--
Using git schema will fail on user that does not have SSH key in
git.sr.ht.
--

_AUR: add package script for Arch Linux user::

all: update the README with the latest implementation::
This include updating the license to GPL v3.0.

all: watch and convert .adoc files during development::

all: convert the adoc during build and serve::

all: realign some structs to minimize memory usage::


[#v0_6_0]
== awwan v0.6.0 (2022-07-04)

This release set minimum Go version to 1.17.

[#v0_6_0_bug_fix]
===  Bug fix

all: fix the #get! statement when executing on local::
+
--
Since fa94025f8e, we change the local statement to be executed using
"/bin/sh", "-c", "<statement>".
This cause the #get! command failed to execute because

* we try to read the input file without permission, and
* we did not set the raw statement required by ExecLocal.
--

[#v0_6_0_enhancements]
===  Enhancements

cmd/awwan: make the "help" and "version" as command::
+
--
Previously, to print the help and version we use the flag package, "-h"
for printing usage and "-v" for printing "version".

The flag should be used to changes the behaviour of command not
terminating the command.
Using and mixing flag as command make the CLI API to be inconsistent.

For example, the following argument is inconsistent,

  $ awwan -h play script.aww 1 -

Instead of executing script.aww, it print the usage and terminate.
--


[#v0_6_0_chores]
===  Chores

all: changes the way to build JavaScript using esbuild::
+
--
Previously, we build the JavaScript files on directory _www by
using TypeScript compiler (tsc).

This changes replace the tsc with esbuild, a Go module that provide
API to convert TypeScript to JavaScript, and use tsc for type checking
only.
--

[#v0_5_0]
== awwan v0.5.0 (2022-03-14)

This release re-lincesing the awwan software under GPL 3.0 or later.

See https://kilabit.info/journal/2022/gpl for more information.


[#v0_4_0]
==  awwan 0.4.0 (2022.02.05)

This release bring new command "serve" to awwan.
The serve command run HTTP server that provide web-user interface to create,
edit, save, and execute script.

[#v0_4_0_new_features]
===  New features

all: implement HTTP API and function to Save file on web-user interface::
+
--
The web-user interface now have button "Save" that save the edited
content of file to storage.
--

all: implement serve command::
+
--
The serve command will run a HTTP server that provide web-user interface
to edit and execute script.

Currently, the web-user interface provide the following features,

* Browsing the workspace
* Running the script on local or remote
--

[#v0_4_0_enhancements]
=== Enhancements

all: make the local statement executed with "/bin/sh -c ..."::
+
--
By using "sh -c", the statement can contains environment variable,
piping, and other shell commands that cannot be supported if executed
directly using native os.Exec.
--

all: expand the environment on statement when executing local script::
+
--
This changes replace the string ${x} or $x in the statements with the
current environment variables values.

For example, statement "mkdir ${HOME}/tmp" will expand the ${HOME} to
the current user home directory.
--

all: use native SFTP to put and get file when possible::
+
--
Previously, the command to put and get file from remote server depends
on installed scp program on the host computer.

In this changes we add the SFTP client and use it as primary function
to put and get file to/from remote when possible and use the scp as
fallback.
--

[#v0_3_0]
==  awwan 0.3.0 (2021.06.09)

go.mod: set the minimum Go to 1.16 and update to share module v0.25.1

[#v0_3_0_enhancements]
=== Enhancements

cmd/awwan: print the awwan version on command usage output::

all: check and return an error if start index is out of range::

all: log error when executing script (local or play)::

all: do not load SSH config if command mode is "local"::
+
--
If the mode is local there is no need to parse and load the SSH config,
since the command to be executed will run on local machine anyway.
--

all: set base dir based on the first .ssh directory that we found::
+
--
Previously, the base directory is set on current working directory.
This limit the way to execute awwan only from the directory
that contains the .ssh directory.

This changes set the environment BaseDir based on the first .ssh
directory that we found from script path up to the "/".  So, user can
execute awwan script from any sub-directories.
--

[#v0_2_1]
==  awwan 0.2.1 (2021.01.18)

Update the share modules which bring fixes to "#put" commands.

[#v0_2_0]
==  awwan 0.2.0 (2020.07.05)

[#v0_2_0_new_features]
===  New features

environment: export the SSH key, user, host, and port::
+
--
By knowing this values, user can use it to invoke other SSH related
command, for example to copy file using `scp`

  scp -i {{.SSHKey}} src {{.SSHUser}}@{{.SSHHost}}:{{.SSHPort}}/dst
--

all: add magic command "#require:"::
+
--
Magic word `#require:` will ensure that the next statement will always
executed when its skipped with start number.
For example, given following script with line number

----
1: #require:
2: echo a
3: echo b
4: #require:
5: echo c
----

executing `awwan local script.aww 3`, will always execute line
number 2 `echo a`, but not line number 5 (because its before line start 3).
--

[#v0_2_0_bug_fixes]
===  Bug fixes

command: change the owner of file when doing `#get!`::
+
--
In case the owner of file is not active user and it does not have
read permission, the "#get!" command will fail when copying command
from remote to local.
--

command: fix magic copy and get command on templates::

[#v0_2_0_enhancements]
===  Enhancements

command: merge sequences of spaces on command into single space::

command: check for single, double, or back quote on command::
+
--
Previously, if command contains quote like,

	echo "a b"

the script will run it as ["echo", `"a`, `b"`] which is not what we
will expected and may cause some command failed to run.

This changes fix the parsing of command string by detecting possible
quote.
--

[#v0_1_0]
==  awwan 0.1.0 (2020.05.30)

Its better late than never.

The first release works for everyday use.
The `local`, `play` command works as it is, and its has been used for
deploying and managing postfix, dovecot, haproxy, and my personal server and
services at kilabit.info.
Also it has been used to deploy Go microservices using Kubernetes using
combination of `gcloud` and `kubectl`.
