:toc:
:sectanchors:
:sectlinks:

awwan is configuration management software, infrastructure as file and
directory layout.
In other words, `awwan` is a command-line interface to shell script, that can
execute multiple lines of commands in local or remote server using shell or
SSH.

Do you have a collection of shell scripts to manage one more similar server?
Do you ever want to execute only part of your script?
Are you get tired with learning others syntax and tools for provisioning
your own server, while you need is a handful knowledge of shell script?

If yes, awwan is the right tools for you.

Features,

* Encryption. Awwan can read and copy encrypted files.
* Encrypted variables. Awwan can read and executed script that contains
  encrypted variables.
* Dynamic script with variables. An awwan script is like shell script but can
  be executed in different remote servers with different values.
* Dynamic script execution. Unlike shell script, awwan can select which
  lines to be executed, either by number or by range.
* Provisioning in local environment using basic shell.
* Provisioning in remote server using SSH and SFTP.


==  Documentation

link:CHANGELOG.html[Changelog]:: History of each awwan release.

link:install.html[Installation]:: Link download and/or install awwan
manually from source code.

link:README.html[Manual page]:: The manual page describe how to use
and setup awwan workspace.

==  Development

https://git.sr.ht/~shulhan/awwan[Repository^]::
Link to the source code.

https://lists.sr.ht/~shulhan/awwan[Mailing list^]::
Place for discussion and sending patches.

https://todo.sr.ht/~shulhan/awwan[Issues^]::
Link to open an issue or request for new feature.

== To-do

* [ ] `#-put:` and `#-put!`, put file as is without parsing.

* [ ] Add option to set file owner and attributes in #put command,
+
--
Example,

	#put!user:group+0600 <src> <dest>

The first option is user, and then separated by ":" is group and then
separated by "+" is attributes.
--

* [ ] replace "play" with "remote". This is breaking changes.

* [ ] use "play" to run script that contains "#local:" and "#remote:".

* [ ] wui: Cleanup stdout and stderr on run.

* [ ] wui: Refresh the tree

* [ ] Cache the script, fstat the script before reading.
+
--
This is quite complex because if the script contains call to `{{.Val ...}}`,
we need also to check if the awwan.env or .awwan.env.vault also changes.
--

* [ ] Cache the environment file

* [ ] Export each of variable as system environment variable with format:
  `SECTION_SUBSECTION_KEY`

// SPDX-FileCopyrightText: 2019 M. Shulhan <ms@kilabit.info>
// SPDX-License-Identifier: GPL-3.0-or-later
